#port??
server:
  port: 9000
#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g8ref-kr.vpc-pub-cdb.ntruss.com:3306/semipig?serverTimezone=Asia/Seoul
    username: semipig
    password: pig123!@#
  servlet:
    multipart:
      max-file-size:
        20MB
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  #mybatis
mybatis:
  type-aliases-package: boot.semipig.dto
  mapper-location:
    - /mapper/**/*.xml